### ISSUE TITLE
Using hardcoded fallback DNS even when a server is configured?

### ISSUE THREAD

**Issue by singpolyma** [MiniDNS/minidns#135]
Any idea why the fallback DNS would be used by `DnssecResolverApi` when the user does have a pihole on their LAN? Issue is that they have firewalled all traffic over 53 except from the pihole, so the fallback just fails.

**Comment by Flowdalic** [comment]
Hi @singpolyma thanks for your interest in MiniDNS.

I think this question, and your other questions #131 and #132, may be answered if you increase the JUL log level of the `org.minidns` package. MiniDNS already uses JUL extensively and ideally would tell you which action it took and why it entered a fallback path. That said, I can't rule out that in some cases log statements are missing. If you identify such situations, then I'd be more than happy to add additional log statements and/or accept PRs doing so.

**Comment by singpolyma** [comment]
this particular issue seems to have been caused by the user's DNS server returning servfail for all SRV lookups
