### ISSUE TITLE
org.minidns:minidns-android21 is missing from the 1.1.1 release

### ISSUE THREAD

**Issue by dugsmith** [MiniDNS/minidns#147]
Thank you for your work on this great library!

I'm trying to upgrade my project from `1.0.5` to `1.1.1`, but I'm using `minidns-android21`, and there doesn't seem to be a version of that built and deployed for `1.1.1`. Can you please publish that?

**Comment by Flowdalic** [comment]
Thanks

It is now called minidns-android23.

**Comment by dugsmith** [comment]
Cool, thank you!
