### ISSUE TITLE
DNSSECClient may return false DNSSEC-negatives: RR results not verified, although RRs are secured by DNSSEC

### ISSUE THREAD

**Issue by arnt** [MiniDNS/minidns#40]
I'm looking at a stack trace from yet another broken DNS cache/forwarder, and this time I noticed that although DNSSECClient is-a ReliableDNSClient it does not fall back to iterative resolution in the way it should.

As I read the code, DNSSECClient performs reliable non-DNSSEC queries, then does the DNSSEC validation using the results of whatever ReliableDNSClient.query() returns, so that if the DNS forwarder is fine in the plain-DNS sense but skimps on the NS section, I get "NSECs must always match to a SOA". I believe that in this case, ReliableDNSClient's semantics imply that DNSSECClient should drop that name server and instead go ask the authoritative servers... perhaps DNSSECClient.isResponseAcceptable() should check that the expected RRs are present, like verifyNsec()?

**Comment by Flowdalic** [comment]
HI @arnt, sorry for the long delay.

If I understood you correctly, then you suggests a new condition in which DNSSECClient.isResponseAcceptable() should decide that the response is not acceptable. Could you elaborate on this condition a little bit and/or rephrase it?

**Comment by arnt** [comment]
August 20? I stayed in a fine hotel that day, but the DNS server I got from DHCP wasn't at all fine. If I did an A lookup I got an A answer, with (IIRC) empty AD/NS sections.

1. Minidns knows that the root zone is signed.
2. Minidns knows whether a delegated zone is signed based on information from the (signed) parent zone.

If the DHCP-supplied DNS server strips information from replies, so that the answers contain the asked-for A/MX/AAAA/whatever, but do not contain any DNSSEC information, then minidns knows from point 1/2 whether the DNS server has thrown away records.

**Comment by Flowdalic** [comment]
> then minidns knows from point 1/2 whether whether the DNS server has thrown away records

That is right but would require MiniDNS to do a zone walk beginning from the root zone to determine if this is case. Not saying that this is an bad idea, just pointing it out.

**Comment by arnt** [comment]
Right, and even a persistent cache might not make that perform well.

But without it, you can ask DNSSECClient for a DNSSEC-enabled record and still get the hotel's captive portal and no error. That "no error" bit shook me. I didn't expect that from DNSSECClient.

**Comment by Flowdalic** [comment]
> But without it, you can ask DNSSECClient for a DNSSEC-enabled record and still get the hotel's captive portal and no error. That "no error" bit shook me. I didn't expect that from DNSSECClient.

Just to clarify: By "no error" you mean that DNSSECClient was able to resolve the query of a DNSSEC secured RR and returned a result, although it did not report that the result was verified/authentic data (cause it was unable to verify).

Right now, that is intentionally behavior of DNSSECClient: You can get false negatives regarding DNSSEC verifyability. A first solution to fix this, would be to wrap the existing DNSSECClient into a ReliableDNSSECClient, which falls back to resolving the query iteratively, starting from the root zone, every time DNSSECClient would return a non-verified positive result. But care must be taken, that those two resolving mechanisms must not share the same cache.

**Comment by Flowdalic** [comment]
I've just pushed [a commit](https://github.com/rtreffer/minidns/commit/0227c356d28ef83ff48a238572cce9c98cfdbd27) which adds `ResolverApi.resolveDnssec()`. This high-level API method should provide a good guarantee that if the result is authenticated via DNSSEC, it will return an verified result. This is because it will eventually fall back doing an iterative query starting from the root nameservers, if the recursive lookup yielded a non authenticated result. The only thing which could also fail this approach is something like a firewall mechanism, which would strip DNSSEC records from answers of remote nameservers.

@arnt Could you the next time you are in such a situation (hotel, captive portal, etc) try the `ResolverApi.resolveDnssec()` API (for example via MiniDNS's REPL) and report you findings? That would be much appreciated.

**Comment by arnt** [comment]
Thanks! I'm going to China in two weeks and will try it on the networks I encounter there, that should be a harsh but not unreasonable test.

**Comment by Flowdalic** [comment]
Closing this. Feel free to reopen or create a new issue if you feel there is the need. I'd also like to point out that MiniDNS 0.4.0-alpha3 is out and looking for alpha testers ;)

**Comment by arnt** [comment]
Oh, I didn't report. Very sorry. It worked well when it could work at all. I'll update to 0.4.0-* in the nearish future.
