### ISSUE TITLE
DnssecResolver.resolveDnnsReliable throws Runtime Exceptions (and more)

### ISSUE THREAD

**Issue by iNPUTmice** [MiniDNS/minidns#62]
The `resolveDnssecReliable()` method throws several exceptions related to DNS sec. (Not all of them are reproducible on all DNS servers)

I even have reports of a NPE but no current stack trace. (At some point the DNSSECMessage was NULL due to the server using a more recent (unstable?) version of DNSSEC or something? Will try to get the actual stack trace.

In any case I believe that all DNSSEC related exceptions should be catched internally and only lead to `authenticated` being set to `false`.

Otherwise I'd have to catch the error and rerun the query.

This issue is not about avoiding this bugs (that might as well be caused by the servers or the entries themselves) but about the handling in minidns.

```
de.measite.minidns.dnssec.DNSSECValidationFailedException: Validation of request to camo.trashserver.net.	IN	AAAA failed: Invalid NSEC!
    at de.measite.minidns.dnssec.DNSSECClient.verifyNsec(DNSSECClient.java:236)
    at de.measite.minidns.dnssec.DNSSECClient.verify(DNSSECClient.java:148)
    at de.measite.minidns.dnssec.DNSSECClient.performVerification(DNSSECClient.java:106)
    at de.measite.minidns.dnssec.DNSSECClient.queryDnssec(DNSSECClient.java:94)
    at de.measite.minidns.hla.DnssecResolverApi.resolveDnssecReliable(DnssecResolverApi.java:107)
    at de.measite.minidns.hla.DnssecResolverApi.resolveDnssecReliable(DnssecResolverApi.java:95)
```

**Comment by Flowdalic** [comment]
Those unchecked exceptions are an issue, that is correct. Please post the stacktrace as soon as you get one in your hands. Then we can take care fixing it.

> In any case I believe that all DNSSEC related exceptions should be catched internally and only lead to authenticated being set to false.

There is a difference between could not verify DNSSEC because
1. things represented by subclasses of `UnverifiedReason`
2. the server returned non-protoocl compliant data

1. causes `authenticated` to be set to false. An example of 2. is shown in your example. And throwing that exception is correct. You can simply catch it at the same place where you catch IOExceptions thrown by MiniDNS.

**Comment by iNPUTmice** [comment]
I see. The reasoning behind my request not not throw an exception was that, despite the signatures being messed up or what ever, we still have the actual records; so not throwing an exception would still leave us with a `ResolverResult<D>` and without the need to re-request the record w/o DNSSEC.

That might be misguided though due to my lack of knowledge about DNS. Feel free to close here.

**Comment by Flowdalic** [comment]
Closing this. Feel free to reopen or create a new issue if you feel there is the need. I'd also like to point out that MiniDNS 0.4.0-alpha3 is out and looking for alpha testers ;)
