### ISSUE TITLE
Release 0.2.5

### ISSUE THREAD

**Issue by Flowdalic** [MiniDNS/minidns#77]
Title says it all. Please release 0.2.5

**Comment by andy-kaminski** [comment]
Any plan to release this? We're also waiting for this fix https://github.com/MiniDNS/minidns/issues/76

**Comment by Flowdalic** [comment]
FYI You don't need to wait for a release, you could just plug in a patched version of `AndroidUsingExec` in MiniDNS and remove the faulty one.

**Comment by DaniPix** [comment]
I'm using it through Smack library that still uses a version with #76 bug, is there a way to plug it there without the necessity to maintain Smack myself ?

**Comment by Flowdalic** [comment]
MiniDNS 0.3.0 has been released.
