### ISSUE TITLE
could not resolve some shake hand issue with you maven repo i guess ... dont know whats going on

### ISSUE THREAD

**Issue by adeelturk** [MiniDNS/minidns#78]
> Could not resolve de.measite.minidns:minidns:[0.1,0.2).
      > Failed to list versions for de.measite.minidns:minidns.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/de/measite/minidns/minidns/maven-metadata.xml.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/de/measite/minidns/minidns/maven-metadata.xml'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/de/measite/minidns/minidns/maven-metadata.xml'.
                  > Remote host closed connection during handshake
   > Could not resolve de.measite.minidns:minidns:[0.1,0.2).
      > Failed to list versions for de.measite.minidns:minidns.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/de/measite/minidns/minidns/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/de/measite/minidns/minidns/maven-metadata.xml'.
               > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/75.126.118.188] failed: Read timed out

**Comment by Flowdalic** [comment]
MiniDNS artifacts are hosted at Maven Central. Your build systems appears to only query Google's repository and jcentral.

**Comment by adeelturk** [comment]
Thanks @Flowdalic
