### ISSUE TITLE
How to get/set dns server ?

### ISSUE THREAD

**Issue by sintanial** [MiniDNS/minidns#84]
1. How to get dns server which resolve my host ? I tried to find in ```ResolverResult``` and ```DnsMessage``` but no result :( ?
2. How to set only my dns server in DnsClient ?

It's needed for me because I try to write utility which test dns performance for specific dns server :)

**Comment by Flowdalic** [comment]
The latest code in master has support for this via the newly introduced `DnsQueryResult` class.

**Comment by Flowdalic** [comment]
Available in MiniDNS 0.4.0-alpha2

**Comment by sintanial** [comment]
Cool, can i use alpha3 in prod ? Or only stable is normal for production ?

**Comment by Flowdalic** [comment]
> can i use alpha3 in prod ?

You can, it is totally up to you. I wont stop you. I provide the same gurantee and warranty as for non-alpha/beta/rc releases: **None**.

**Comment by sintanial** [comment]
Thanks for improve, very useful ;)
