### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by eakteam** [MiniDNS/minidns#97]
Hi, everything was going fine before. After adding some native libs on my app it is throwing this exception :

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: LdTb;
       at org.minidns.dnsserverlookup.AndroidUsingExec.isAvailable(AndroidUsingExec.java:61)
       at org.minidns.DnsClient.addDnsServerLookupMechanism(DnsClient.java:399)
       at org.minidns.DnsClient.(SourceFile:4)
```

I am using compileSdkVersion 28

**Comment by Flowdalic** [comment]
> LdTb;

Is there some code obfuscation tool involved? Am I right to assume you are using MiniDNS 0.3.3?

**Comment by eakteam** [comment]
The crash is happening on `minidns-client:0.4.0-alpha3`. Also i have checked to in my R8/Proguard rules, already added : `-keep class org.minidns.dnsserverlookup.**` , but it is still crashing, i don't know why.

The crash on firebase/crashlytics/logs says : 

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: LCv1;
       at org.minidns.dnsserverlookup.AndroidUsingExec.isAvailable(AndroidUsingExec.java:61)
       at org.minidns.DnsClient.addDnsServerLookupMechanism(DnsClient.java:399)
       at org.minidns.DnsClient.(SourceFile:4)
```

**Comment by Flowdalic** [comment]
Does it also crash if you completely disable ProGuard?

**Comment by eakteam** [comment]
@Flowdalic , when i am testing on debug mode, the crash don't happen immediately and not always. But sometimes yes it does crash

**Comment by eakteam** [comment]
For Android > API 21 if i add on Application Class : `DnsClient.addDnsServerLookupMechanism(AndroidUsingLinkProperties.setup(this)` , it is crashing immediately when applying R8 or Proguard

**Comment by Flowdalic** [comment]
> when i am testing on debug mode, the crash don't happen immediately and not always. But sometimes yes it does crash

How does the (non-obfuscated) stacktrace look like if ProGuard is disabled?

**Comment by eakteam** [comment]
@Flowdalic  I will try and will get back to this again. Thanks for your support.

**Comment by eakteam** [comment]
@Flowdalic , when i apply R8/Proguard but adding this `-dontobfuscate` , it is not crashing anymore. I don't understand why because in fact even if i apply obfuscations still have added keep rules for `-keep class org.minidns.dnsserverlookup.** { *; }` and it should not obfuscate it. 

I understand that this maybe is not bug of this library itself, but maybe something can be refactored to better function ?

Best Regards

**Comment by eakteam** [comment]
With obfuscation enabled this is my rules which everything works OK.

```
-keep, allowoptimizationclass org.minidns.dnsserverlookup.**
-keep, allowoptimization class org.minidns.DnsClient   //Adding this second line solve the issue
```

You can close this issue if nothing can be done through the library itself to better initialize classes
